# Generated by Django 2.0.1 on 2018-01-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_critical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=16)),
                ('event_source', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('machine_name', models.CharField(max_length=32)),
                ('events_count', models.IntegerField()),
                ('event_user', models.CharField(max_length=64)),
                ('event_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='App_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=16)),
                ('event_source', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('machine_name', models.CharField(max_length=32)),
                ('events_count', models.IntegerField()),
                ('event_user', models.CharField(max_length=64)),
                ('event_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='App_warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=16)),
                ('event_source', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('machine_name', models.CharField(max_length=32)),
                ('events_count', models.IntegerField()),
                ('event_user', models.CharField(max_length=64)),
                ('event_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System_critical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=16)),
                ('event_source', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('machine_name', models.CharField(max_length=32)),
                ('events_count', models.IntegerField()),
                ('event_user', models.CharField(max_length=64)),
                ('event_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System_error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=16)),
                ('event_source', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('machine_name', models.CharField(max_length=32)),
                ('events_count', models.IntegerField()),
                ('event_user', models.CharField(max_length=64)),
                ('event_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System_warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=16)),
                ('event_source', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('machine_name', models.CharField(max_length=32)),
                ('events_count', models.IntegerField()),
                ('event_user', models.CharField(max_length=64)),
                ('event_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
