# Generated by Django 2.0.1 on 2018-02-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('win_events', '0003_proceed_date_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_critical',
            name='events_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='app_error',
            name='events_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='app_warning',
            name='events_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='system_critical',
            name='events_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='system_error',
            name='events_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='system_warning',
            name='events_count',
            field=models.IntegerField(null=True),
        ),
    ]
